//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIexamen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIexamen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultConnection.
        /// </summary>
        internal static string ConnectionDB {
            get {
                return ResourceManager.GetString("ConnectionDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la DB.
        /// </summary>
        internal static string ErrorDB {
            get {
                return ResourceManager.GetString("ErrorDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS_Product.
        /// </summary>
        internal static string SPCreateProduct {
            get {
                return ResourceManager.GetString("SPCreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL_Product.
        /// </summary>
        internal static string SPDeleteProduct {
            get {
                return ResourceManager.GetString("SPDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_Products_PAG.
        /// </summary>
        internal static string SPGetProductsPag {
            get {
                return ResourceManager.GetString("SPGetProductsPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEL_Product.
        /// </summary>
        internal static string SPSelectProduct {
            get {
                return ResourceManager.GetString("SPSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_Product.
        /// </summary>
        internal static string SPUpdProduct {
            get {
                return ResourceManager.GetString("SPUpdProduct", resourceCulture);
            }
        }
    }
}
